### PR TITLE
Enable IPv6 and Multicast networking

### PR DESCRIPTION
**Pull request by apalrd**
IPv6 should be enabled for network-connected devices. IPv6 also requires multicast.

### CODE REVIEW

**Comment by dx9s** [comment]
@apalrd 
I don't fully understand the need to have a full IPv4+v6 stack in an embedded device that is already limited in RAM.
If somebody needs IPv6 for some purpose than they can indeed rebuilt the kernel. I don't own the DUO.... YET! so I have a few questions.

I don't know if KO (kernel modules) are enabled or if it's a single kernel object with all enabled options built-in. If the kernel supports the ability to runtime load and unload kernel modules, then sure compile them as modules... but in an embedded scenario with limited RAM (and I'd want to avoid swap at all cost), I'd want the kernel as lean as possible for multiple reasons (save memory, reduce attack vectors, etc.)

I see the DUO clearly as a IoT thing that could connect to a remote internet and not having to deal with 4-to-6 issues. In most cases IPv4 for simple local access seems like a good compromise to ship as-is. 

The second core w/ RTOS running whatever ION stands for (image recognition it seems) can be disabled for more of the 64MB of RAM I understand.

I think that *IF* kernel module support could be enabled (if it isn't already) IPv6 as a module makes sense so people don't have to compile from source to get a lean kernel that meets their needs.

P.S.> discovered this DUO module from your video and have one on order.

**Comment by apalrd** [comment]
There are a few flags changed here, but in general, this enables IPv6 (which requires multicast) and also IPv4 multicast. Both are very useful for embedded apps. The kernel is already configured for module loading (and some of the video modules are loaded this way), but the (static) inclusion of IPv6 and multicast grows the kernel by only 14k.

IPv6 is already widely used in IoT devices (i.e. the new Matter family of protocols requires IPv6). Multicast (on v4 and v6) is separately useful for mdns and dns service discovery, which are both also commonly used in IoT gadgets. IPv6 is also the current version of the internet protocol and we have no real reason to exclude it on a Linux system.

**Comment by dkay0670** [comment]
I think that if you need to save 14KB off your kernel, you'd probably building one yourself that has only **exactly** what you need.

**Comment by dx9s** [comment]
I agree 14KB on disk isn't bad + allocated RAM to manage ipv6 settings/sockets -- good to know. I was guessing it was a bit larger. Also if size is an issue, one would indeed be making a custom one. Still building as a module is an interesting compromise.

I did go back and read the entire config file for kernel things like module support (and which prempt model was in use, curious if anybody has used prempt_rt on this hardware). Interested in how the RTOS on the second core could negate the need for more precise timing on the Linux side and how the two cores interact during runtime. It sounds at some point MILKV will also provide a build to have both cores available to Linux as well.

**Comment by nomadium** [comment]
For what is worth, I have been running my board with this patch for a week already and it works perfectly fine. I run an IPv6- only network at my homelab so I find rather useful to have the board auto-configured with a routable IPv6 address.

**Review by carbonfix — APPROVED** [review]

**Pull request merged**
